### ISSUE TITLE
[Issue#1][Функционал приложения] Загрузка списка задач

### ISSUE THREAD

**Issue by Veleri** [SummertimeS4dness/TaskManager#1]
При старте приложения, пользователь должен выбрать с каким списком он хочет работать:
1) продолжить работу с уже существующим списком;
2) создать новый;
3) загрузить уже существующий список.
Тебе нужно добавить пункт (1) и настроить работу пункта (3).
Открыть существующий файл не удается:
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -2
	at java.lang.String.substring(String.java:1967)
	at com.company.Model.TaskIO.read(TaskIO.java:154)
	at com.company.Model.TaskIO.readText(TaskIO.java:242)
	at com.company.Controller.MainController.existingFileTaskHandler(MainController.java:469)
	at com.company.View.ConsoleView$2.Invoke(ConsoleView.java:21)
	at com.company.View.menu.Menu.show(Menu.java:133)
	at com.company.View.ConsoleView.run(ConsoleView.java:29)

**Comment by SummertimeS4dness** [comment]
Коммит [Issue#1][Функционал приложения] + Коммит [Issue#1][Функционал приложения] дополнительный (знаю что одна правка - один коммит, но я забыл закоммитить один файл)

**Comment by SummertimeS4dness** [comment]
[Tasks.txt](https://github.com/SummertimeS4dness/TaskManager/files/1711835/Tasks.txt)
Файл для теста, проверено, открывается. Также можно создать новый файл в самой программе и открыть его
